const nodemailer = require("nodemailer"); // npm package to send mail
const xlsx = require("xlsx"); // npm package to read xlsx
const fs = require("fs"); // reads files
const config = JSON.parse(fs.readFileSync("./signature.json", "utf8"));
const signature = `<p>Thanks,<br>${config[0].name}<br>Phone: ${config[0].phone_1}, ${config[0].phone_2}</p>`;

// Steps:
// 1 - Configure the host email details
// 2 - Read the xlsx file and convert the contents to json format
// 3 - Format excel data to json
// 4 - Send mail

// 1 - Host Mail Configuration
var mailSender = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: "adlerrussel01@gmail.com",
    pass: "zboemwcpsqyppfmy", // this is the app password generated by Google under 2FA for adlerrussel01@gmail.com and appname = Mail SMTP
  },
});

readData();

// 2 - Reads data from Excel File
function readData() {
  const excelWorkBook = xlsx.readFile("./Data.xlsx");
  const sheetNames = excelWorkBook.SheetNames[0];
  const sheetValue = excelWorkBook.Sheets[sheetNames];
  var excelData = xlsx.utils.sheet_to_json(sheetValue);
  if (excelData.length) {
    for (let i = 0; i < excelData.length; i++) {
      formatData(excelData[i]);
    }
  } else {
    console.error("Error: No Data Found in Excel");
  }
}
// 3 - Formats excel data into html format
function formatData(data) {
  try {
    var details = {};
    var emailContent = "";
    var emailParagraphs = "";
    var emailContentSplit =
      data["Email Content"] && data["Email Content"].length
        ? data["Email Content"].split("<>")
        : "NA";
    for (let str of emailContentSplit) {
      emailParagraphs += `${str}<br>`;
    }
    var val =
      data["Client Name"] && data["Client Name"].split(" ").length > 0
        ? data["Client Name"].split(" ")[0]
        : "NA";
    emailContent += `<p>Hello ${val},</p><p>${emailParagraphs}</p>${signature}`;

    details.from = "adlerrussel01@gmail.com";
    details.to = data["Client Email"];
    details.subject = data["Email Subject"];
    details.html = emailContent;
    sendMail(details, val);
  } catch (error) {
    console.error("Error in function formatData: ", error);
  }
}
// 4 - Sends Mail
function sendMail(mailDetails, val) {
  console.log(`Sending Email to ${val} \n`);
  mailSender.sendMail(mailDetails, function (error) {
    if (error) {
      console.error(error);
    } else {
      console.log(`Email sent to ${val} successfully!`);
    }
  });
}

// TODO: Scheduling
// https://stackoverflow.com/questions/59517087/how-to-schedule-the-node-js-script-to-run-automatically-on-windows

// Resources:
// https://wpmailsmtp.com/gmail-less-secure-apps/
// https://stackoverflow.com/questions/72530276/how-to-send-emails-with-google-using-nodemailer-after-google-disabled-less-sure
// https://stackoverflow.com/questions/73604854/how-to-read-the-excel-sheet-data-in-node-js
// https://www.youtube.com/watch?v=1XUJgdFRK2M
